[package]
name = "noted"
version = "0.1.0"
edition = "2021"
authors = ["Vili Ikäheimo <vili.vikaheim@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
rusqlite = "0.29.0"
text_io = "0.1.12"
